# Generated by Django 2.2 on 2022-03-21 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MadLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mad_lib_name', models.CharField(max_length=200, unique=True)),
                ('mad_lib_desc', models.CharField(max_length=200)),
                ('story', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('position', models.PositiveSmallIntegerField()),
                ('mad_lib_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mad_libs.MadLib')),
            ],
        ),
    ]
